using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using GTA;
using GTA.Math;
using GTA.Native;

namespace ARS;

public class ARS : Script
{
	public enum TerrainTypes
	{
		Sand = 1288448767,
		RockySand = -1595148316,
		Gravel = -1885547121,
		GravelGrass = 2128369009,
		LooseGravel = 510490462,
		Rock = -840216541,
		MoreTarmac = 1187676648,
		Tarmac = 282940568,
		WetTarmac = 999829011,
		Grass = 1286696947,
		FullGrass = -461750719,
		ShortGrass = 1333033863
	}

	private class MenuItemDefinition
	{
		public Func<string> Name;

		public Func<string> ValueSuffix;

		public Action<int> OnAdjust;

		public Action OnAccept;

		public bool KeepMenuOpen;
	}

	private enum GridSort
	{
		Power,
		PowerDescendent,
		TopSpeed,
		TopSpeedDescendent,
		Random
	}

	public enum LogImportance
	{
		Info,
		Error,
		Fatal
	}

	public enum DrawTextAlign
	{
		Center,
		Left,
		Right
	}

	public enum DrawTextFont
	{
		Default,
		Italics,
		Squared
	}

	public static Dictionary<Vector3, string> ImmersiveJoins = new Dictionary<Vector3, string>();

	public static float TracjectoryProjectionSeconds = 1f;

	public static List<TrackPoint> TrackPoints = new List<TrackPoint>();

	public static List<CornerPoint> CornerPoints = new List<CornerPoint>();

	public static List<Vehicle> GlobalTraffic = new List<Vehicle>();

	public static List<string> KnownTracks = new List<string>();

	public static int RaceReward = 0;

	public static ScriptSettings SettingsFile;

	public static ScriptSettings DevSettingsFile;

	public static bool HideHudMode = false;

	public static Dictionary<Options, bool> OptionValuesList = new Dictionary<Options, bool>
	{
		{
			Options.ShowAggro,
			false
		},
		{
			Options.ShowInputs,
			false
		},
		{
			Options.ShowTrackAnalysis,
			false
		},
		{
			Options.ShowPhysics,
			false
		},
		{
			Options.UseNearbyCars,
			false
		},
		{
			Options.ReverseRoute,
			false
		}
	};

	public static List<Prop> CustomProps = new List<Prop>();

	public static List<Prop> AutoGeneratedProps = new List<Prop>();

	public static int OptionHovered = 0;

	public static List<Options> OptionsList = new List<Options>();

	public static List<Racer> LeaderboardFinish = new List<Racer>();

	private bool IsDroneMode = true;

	public static Prop FreecCamRide = null;

	public static PedHash[] StreetRacerModels = new PedHash[5]
	{
		PedHash.Car3Guy2,
		PedHash.Vinewood02AFY,
		PedHash.Stwhi02AMY,
		PedHash.StrPunk02GMY,
		PedHash.Stbla02AMY
	};

	public static List<Model> RacerModels = new List<Model> { "a_m_y_motox_01", "a_m_y_motox_02" };

	public static RaceState RaceStatus = RaceState.None;

	public static ulong steeroffset = 0uL;

	public static ulong throttleOffset = 0uL;

	public static ulong brakeOffset = 0uL;

	public static ulong handlingPtr = 0uL;

	public static ulong wheelsPtr = 0uL;

	public static ulong numwheelsoffset = 0uL;

	public static List<int> Other = new List<int> { 555004797, -399872228, -1447280105, 722686013 };

	public static List<int> Road = new List<int> { 1187676648, 282940568, -108464011, 1187676648, -1084640111 };

	public static List<int> Dirt = new List<int>
	{
		1144315879, 510490462, -1907520769, -1885547121, -700658213, 2128369009, -1595148316, -765206029, 509508168, 1333033863,
		951832588, -840216541, -1907520769, 510490462, -1942898710
	};

	public static List<int> Sand = new List<int> { 1288448767 };

	public static List<string> HelpMessages = new List<string>();

	public static List<Racer> Racers = new List<Racer>();

	public static int catchupPos = 0;

	public static List<Vector3> Path = new List<Vector3>();

	public static Dictionary<int, float> Angles = new Dictionary<int, float>();

	public static Dictionary<int, float> MultiplierInTerrain = new Dictionary<int, float>();

	public static Dictionary<int, float> WideDict = new Dictionary<int, float>();

	public static Dictionary<int, float> EditWideDict = new Dictionary<int, float>();

	public static List<Prop> TrackLimits = new List<Prop>();

	public static XmlDocument CurrentFile = null;

	private static bool routeEditMode = false;

	public static int DebugVisual = 0;

	private int TimeToFinishRace = 0;

	private float TimeScale = 1f;

	private float IdealTimeScale = 1f;

	private int GameTimeRef = 0;

	private int GametimerefLong = 0;

	private bool Loaded = false;

	private bool IsLoadingScript = false;

	private Task LoadScriptTask = null;

	private Dictionary<string, string> TrackTags = new Dictionary<string, string>();

	private static ulong steerAngle = 0uL;

	private List<Vector3> RouteSection = new List<Vector3>();

	private Vector3 rBezier = Vector3.Zero;

	private float scale = 1.5f;

	private int wide = 5;

	private int PathDisplayFidelity = 1;

	private int GametimeCountDown = 0;

	private int MaxCountDown = 7;

	private int CountDown = 7;

	private Vector3 FreeCamMovement = Vector3.Zero;

	private Vector3 FreeCamRotation = Vector3.Zero;

	public static Scaleform scaleform = new Scaleform("INSTRUCTIONAL_BUTTONS");

	public static Scaleform racertext = null;

	public static Scaleform debugFrontend = new Scaleform("instructional_buttons");

	public static Scaleform floatingtext = new Scaleform("HUD_FLOATING_HELP_TEXT");

	public static Scaleform SCCountdown = new Scaleform("MP_BIG_MESSAGE_FREEMODE");

	public static List<string> FilteredTrackList = new List<string>();

	public static string TrackFilter = "airport";

	public static string DisciplineFilter = "sports";

	private Dictionary<string, string> RacerTags = new Dictionary<string, string>();

	public static int TrackListPos = 0;

	private readonly Dictionary<Options, MenuItemDefinition> MenuItemDefinitions = new Dictionary<Options, MenuItemDefinition>();

	private Vehicle debugTrailer;

	private Dictionary<int, Vector3> ExhaustOffsets = new Dictionary<int, Vector3>();

	private List<Vector3> MiniaturizedPath = new List<Vector3>();

	private int GameTimeShort = Game.GameTime;

	private int secInteval = 0;

	private Dictionary<Vector3, string> NeabyImmersiveJoins = new Dictionary<Vector3, string>();

	public List<Vector3> AccelerationVector = new List<Vector3>();

	private Vector3 lSpeed = Vector3.Zero;

	private int NextInLine = 0;

	private int GameTimeNextInLine = 0;

	private Vector3 GsClamp = new Vector3(1f, 1f, 1f);

	private Vector3 directionClamp = new Vector3(1f, 1f, 1f);

	private bool InFreeCam = false;

	private float CamIntendedHeight = 4f;

	public static List<Vector3> GridPositions = new List<Vector3>();

	private List<int> FlareFX = new List<int>();

	public static bool IsPointToPoint = false;

	public bool listenmode = false;

	public Dictionary<int, int> DistToPercent = new Dictionary<int, int>();

	private static Random rnd = new Random();

	private int intendedOpponents = 5;

	private List<PersonalitySet> personalitySets = new List<PersonalitySet>();

	private VehicleColor[] randomcolors = new VehicleColor[5]
	{
		VehicleColor.MetallicRed,
		VehicleColor.MetallicRaceYellow,
		VehicleColor.MetallicBlue,
		VehicleColor.MetallicOrange,
		VehicleColor.MetallicSteelGray
	};

	private List<XmlDocument> CachedCandidates = new List<XmlDocument>();

	public void StartLoadScript()
	{
		if (!IsLoadingScript)
		{
			DisplayHelpTextTimed("Loading ~b~ARS.~w~ May take a while.", 20000);
			Loaded = false;
			IsLoadingScript = true;
			LoadScriptTask = Task.Run(delegate
			{
				FillKnownDisciplines(allowScriptYield: false);
				FillKnownTracks(allowScriptYield: false);
				ReFilterKnownTracks(TrackFilter);
			});
		}
	}

	private void HandleLoadScriptTask()
	{
		if (IsLoadingScript && LoadScriptTask != null && LoadScriptTask.IsCompleted)
		{
			if (LoadScriptTask.IsFaulted)
			{
				Loaded = false;
				Exception ex = LoadScriptTask.Exception?.GetBaseException();
				Log(LogImportance.Error, "Initialization failed: " + ((ex != null) ? ex.Message : "Unknown error"), forced: true);
				DisplayHelpTextTimed("~r~ARS failed to load. Check log.", 4000);
			}
			else
			{
				FillCachedCandidates(DisciplineFilter, intendedOpponents);
				Log(LogImportance.Info, "Initialization complete.", forced: true);
				DisplayHelpTextTimed("~g~ARS has loaded.", 2000);
				HelpMessages.Add("Press ~INPUT_SPRINT~ + ~INPUT_CONTEXT~ to open the ~b~ARSe~w~ menu.");
				Loaded = true;
			}
			IsLoadingScript = false;
			LoadScriptTask = null;
		}
	}

	public ARS()
	{
		base.Tick += OnTick;
		base.Aborted += OnAbort;
		File.WriteAllText("scripts\\ARS\\Log.log", "----------------------------");
		Log(LogImportance.Info, "Script initialized - " + DateTime.Now.ToString());
		File.AppendAllText("scripts\\ARS\\Log.log", "\n----------------------------");
		LoadSettings();
		string text = "ARS";
		string text2 = "0.0.0.0";
		string text3 = "30/09/2018";
		Assembly executingAssembly = Assembly.GetExecutingAssembly();
		AssemblyName name = executingAssembly.GetName();
		Version version = name.Version;
		text2 = version.ToString() + " ~o~[PUBLIC BETA]~w~";
		text3 = File.GetLastWriteTimeUtc("scripts/ARS/ARS.dll").ToString();
		UI.Notify("~b~" + text + "~g~e~w~~y~ " + text2 + "~n~Build: ~g~" + text3);
	}

	public static float LaneApproach(float DistPercent)
	{
		float result = 0f;
		if (DistPercent >= 80f)
		{
			result = map(DistPercent, 80f, 100f, 95f, 100f, clamp: true);
		}
		else if (DistPercent >= 60f)
		{
			result = map(DistPercent, 60f, 80f, 80f, 95f, clamp: true);
		}
		else if (DistPercent >= 40f)
		{
			result = map(DistPercent, 40f, 60f, 50f, 80f, clamp: true);
		}
		else if (DistPercent >= 20f)
		{
			result = map(DistPercent, 20f, 40f, 25f, 50f, clamp: true);
		}
		else if (DistPercent >= 0f)
		{
			result = map(DistPercent, 0f, 20f, 0f, 25f, clamp: true);
		}
		return result;
	}

	public void FillKnownTracks(bool allowScriptYield = true)
	{
		TrackTags.Clear();
		ImmersiveJoins.Clear();
		Log(LogImportance.Info, "Learning available tracks...");
		List<string> list = Directory.GetDirectories("scripts\\ARS\\Tracks").ToList();
		list.Add("scripts\\ARS\\Tracks");
		foreach (string item in list)
		{
			int num = 0;
			foreach (string item2 in Directory.EnumerateFiles(item))
			{
				string fileName = System.IO.Path.GetFileName(item2);
				Log(LogImportance.Info, item2 + " - [" + string.Join(", ", GetTrackTags(item2)) + "]");
				TrackTags.Add(item2, string.Join(", ", GetTrackTags(item2)));
				if (!ImmersiveJoins.ContainsKey(GetTrackStartPos(item2)))
				{
					ImmersiveJoins.Add(GetTrackStartPos(item2), item2);
				}
				num++;
				if (allowScriptYield && num > 5)
				{
					DisplayHelpTextTimed("Loading " + fileName, 5000);
					num = 0;
					Script.Yield();
				}
			}
		}
		KnownTracks = Directory.GetFiles("scripts\\ARS\\Tracks").ToList();
		Log(LogImportance.Info, "Done.");
		Log(LogImportance.Info, "-------------");
	}

	public static List<string> GetTrackTags(string path)
	{
		XmlDocument xmlDocument = new XmlDocument();
		xmlDocument.Load(path);
		int num = 0;
		while (xmlDocument == null && num < 1000)
		{
			num++;
			xmlDocument.Load(path);
		}
		List<string> list = new List<string>();
		list.Add(System.IO.Path.GetFileName(path).ToLowerInvariant());
		XmlNodeList xmlNodeList = xmlDocument.SelectNodes("//Tags).ToString();
		xmlNode2.AppendChild(xmlNode4);
		List<string> list = new List<string>();
		string text2 = text;
		text2 = text2.Replace("-", "");
		text2 = text2.Replace("/", "");
		text2 = text2.Replace(" ", "");
		text2 = text2.Replace("+", "");
		list.Add(xmlNode4.InnerText);
		list.Add(text);
		list.Add(text2);
		XmlNode xmlNode5 = xmlDocument.CreateElement("Disciplines");
		foreach (string item in list)
		{
			XmlNode xmlNode6 = xmlDocument.CreateElement("Discipline");
			xmlNode6.InnerText = item.ToLowerInvariant();
			xmlNode5.AppendChild(xmlNode6);
		}
		xmlNode2.AppendChild(xmlNode5);
		xmlNode3 = xmlDocument.CreateElement("Model");
		XmlNode xmlNode7 = xmlNode3;
		int num = (int)h;
		xmlNode7.InnerText = num.ToString();
		xmlNode2.AppendChild(xmlNode3);
		XmlAttribute xmlAttribute = xmlDocument.CreateAttribute("ModelName");
		xmlAttribute.InnerText = h.ToString();
		xmlNode3.Attributes.Append(xmlAttribute);
		xmlNode.AppendChild(xmlNode2);
		xmlDocument.AppendChild(xmlNode);
		xmlDocument.Save("scripts\\\\ARS\\Vehicles\\" + text + ".xml");
		UI.ShowSubtitle("~b~Vehicle saved succesfully.~w~~n~Filename: ~g~" + text + ".xml");
	}

	public static bool IsBetweenRange(float n, float a, float b)
	{
		return n > a && n < b;
	}

	public static Vector3 Project(Vector3 pos, Vector3 dir, float mod, int m)
	{
		return Quaternion.RotationAxis(Vector3.WorldUp, (float)Math.PI / 180f * (mod * (float)m)) * (dir * m);
	}
}
