using GTA;
using GTA.Math;
using GTA.Native;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Xml;

namespace ARS
{
    public static class TrackLoader
    {
        public static XmlDocument LoadTrackFile(string trackname = null)
        {
            ARS.Log(ARS.LogImportance.Info, "Loading " + trackname);
            return TrackRepository.Load(trackname);
        }

        public static void LoadTrack(ARS ars, XmlDocument xmlFile)
        {
            ARS.Log(ARS.LogImportance.Info, "Loading track");
            if (xmlFile == null)
            {
                UI.Notify("~r~Invalid track file.");
                return;
            }
            if (!ars._freeCam.IsActive) Function.Call(Hash.DO_SCREEN_FADE_OUT, 200);
            ars.SetLoadingPromptText("Loading track...");
            Script.Wait(500);

            ARS.CurrentFile = xmlFile;
            foreach (Prop p in ARS.CustomProps) if (ARS.CanWeUse(p)) p.Delete();
            foreach (Prop p in ARS.AutoGeneratedProps) if (ARS.CanWeUse(p)) p.Delete();
            foreach (Prop p in ARS.TrackLimits) if (ARS.CanWeUse(p)) p.Delete();
            ARS.Angles.Clear();
            ARS.RouteNodes.Clear();
            ARS.NodeHalfWidths.Clear();
            ARS.TrackLimits.Clear();

            XmlNode r = xmlFile.SelectSingleNode("Data");

            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");

            foreach (XmlElement prop in r.SelectNodes("Objects/Prop"))
            {
                string x = "0";
                string y = "0";
                string z = "0";
                if (ARS.NodeExists(prop, "X") && ARS.NodeExists(prop, "Y") && ARS.NodeExists(prop, "Z"))
                {
                    x = prop.SelectSingleNode("X").InnerText;
                    y = prop.SelectSingleNode("Y").InnerText;
                    z = prop.SelectSingleNode("Z").InnerText;
                }

                bool isDynamic = false;

                if (ARS.NodeExists(prop, "IsDynamic")) bool.TryParse(prop.SelectSingleNode("IsDynamic").InnerText, out isDynamic);

                float fx = 0f;
                float.TryParse(x, out fx);
                float fy = 0f;
                float.TryParse(y, out fy);
                float fz = 0f;
                float.TryParse(z, out fz);
                Vector3 pos = new Vector3(fx, fy, fz);
                if (ARS.NodeExists(prop, "RotX") && ARS.NodeExists(prop, "RotY") && ARS.NodeExists(prop, "RotZ"))
                {
                    x = prop.SelectSingleNode("RotX").InnerText;
                    y = prop.SelectSingleNode("RotY").InnerText;
                    z = prop.SelectSingleNode("RotZ").InnerText;
                }
                fx = 0f;
                float.TryParse(x, out fx);
                fy = 0f;
                float.TryParse(y, out fy);
                fz = 0f;
                float.TryParse(z, out fz);
                Vector3 rot = new Vector3(fx, fy, fz);

                if (ARS.NodeExists(prop, "Model"))
                {
                    int hash = 0;
                    int.TryParse(prop.SelectSingleNode("Model").InnerText, out hash);
                    if (hash != 0 && new Model(hash).IsValid)
                    {
                        Prop myprop = World.CreateProp(hash, pos, rot, false, false);
                        myprop.Position = pos;
                        Function.Call(Hash.SET_ENTITY_DYNAMIC, myprop, isDynamic);
                        Function.Call(Hash.FREEZE_ENTITY_POSITION, myprop, !isDynamic);
                        Function.Call(Hash.SET_OBJECT_PHYSICS_PARAMS, myprop, 200f * myprop.Model.GetDimensions().Length(), 1f);

                        if (prop.SelectSingleNode("TextureVariation") != null) Function.Call(Hash._0x971DA0055324D033, myprop, int.Parse(prop.SelectSingleNode("TextureVariation").InnerText));

                        ARS.CustomProps.Add(myprop);
                    }
                }
            }
            List<XmlElement> routeNodes = new List<XmlElement>();
            foreach (XmlElement e in r.SelectNodes("Route/Point")) routeNodes.Add(e);

            if (ARS.DebugToggles[Options.ReverseRoute])
            {
                routeNodes.Reverse();
                UI.Notify("~g~Route is reversed.");
            }

            int i = 0;
            float W = 5;
            float oldW = 0;
            foreach (XmlElement e in routeNodes)
            {
                string x = e.SelectSingleNode("X").InnerText;
                string y = e.SelectSingleNode("Y").InnerText;
                string z = e.SelectSingleNode("Z").InnerText;

                float fx = 0f;
                float.TryParse(x, out fx);
                float fy = 0f;
                float.TryParse(y, out fy);
                float fz = 0f;
                float.TryParse(z, out fz);
                Vector3 pos = new Vector3(fx, fy, fz);

                float.TryParse(e.SelectSingleNode("Wide").InnerText, out W);

                if (ARS.RouteNodes.Count > 5) W = ARS.Clamp(W, oldW - 0.25f, oldW + 0.25f);

                if (e.SelectSingleNode("RacingLine") != null && ARS.SettingsFile.GetValue<bool>("GENERAL_SETTINGS", "ReverseRoutes", false) == false)
                {
                    float racingline = 0.0f;
                    float.TryParse(e.SelectSingleNode("RacingLine").InnerText, out racingline);
                }

                ARS.RouteNodes.Add(pos);
                ARS.NodeHalfWidths.Add(i, W);
                oldW = W;
                i++;
            }

            // Detect circuit vs point-to-point BEFORE GenerateRouteInfo so the geometry pass
            // (Angle/Direction/Elevation/PreciseCurveRadius) and BuildApexCorners can wrap node
            // indices across the start/finish seam. Without this, corners sitting on the finish
            // line are invisible to the apex table on circuits.
            ARS.IsPointToPoint = false;
            if (ARS.RouteNodes[0].DistanceTo(ARS.RouteNodes[ARS.RouteNodes.Count - 1]) > 20) ARS.IsPointToPoint = true;

            GenerateRouteInfo();

            Script.Wait(1000);
            ARS.Log(ARS.LogImportance.Info, "Loading props");
            ars.SetLoadingPromptText("Loading props...");
            BuildTrackLimits(ARS.RouteNodes, ARS.NodeHalfWidths, ARS.CurrentFile, ARS.IsPointToPoint, ars._intendedOpponents, ARS.TrackLimits, ars._flareFx, ARS.GridPositions);

            if (ARS.CanWeUse(Game.Player.Character.CurrentVehicle)) Game.Player.Character.CurrentVehicle.Position = ARS.RouteNodes[0]; else Game.Player.Character.Position = ARS.RouteNodes[20];
            if (ARS.CanWeUse(ARS.FreeCamRide)) ARS.FreeCamRide.Position = ARS.RouteNodes[5] + new Vector3(0, 0, 20);
            ars.SetLoadingPromptText("Finished loading props");
            Function.Call(Hash._0x10D373323E5B9C0D);
            ars.SetSPLVisibility(false);

            ARS.Log(ARS.LogImportance.Info, "Loaded track");
        }

        public static void GenerateRouteInfo()
        {
            ARS.Log(ARS.LogImportance.Info, "Generating route info...");
            ARS.TrackPoints.Clear();
            while (ARS.TrackPoints.Count < ARS.RouteNodes.Count)
            {
                int node = ARS.TrackPoints.Count;
                ARS.TrackPoints.Add(new TrackPoint { Node = node, Position = ARS.RouteNodes[node] });
            }

            int nodeCount = ARS.RouteNodes.Count;
            foreach (TrackPoint point in ARS.TrackPoints)
            {
                int average = (int)(point.TrackHalfWidth * 2);
                bool canCompute = ARS.IsPointToPoint
                    ? point.Node > 50 && point.Node < nodeCount - 50
                    : point.Node >= 0 && point.Node < nodeCount;

                if (canCompute)
                {
                    Vector3 left = (ARS.RouteNodes[point.Node] - ARS.RouteNodes[Wrap(point.Node - average, nodeCount)]).Normalized;
                    Vector3 forward = (ARS.RouteNodes[Wrap(point.Node + average, nodeCount)] - ARS.RouteNodes[point.Node]).Normalized;
                    point.Direction = (ARS.RouteNodes[Wrap(point.Node + 2, nodeCount)] - ARS.RouteNodes[Wrap(point.Node - 2, nodeCount)]).Normalized;
                    point.Elevation = (ARS.RouteNodes[Wrap(point.Node + 3, nodeCount)] - ARS.RouteNodes[Wrap(point.Node - 3, nodeCount)]).Normalized.Z * 90f;
                    left.Z = 0f;
                    forward.Z = 0f;
                    point.Angle = Vector3.SignedAngle(left, forward, Vector3.WorldUp);
                    if (float.IsNaN(point.Angle) || float.IsInfinity(point.Angle)) point.Angle = 0f;
                    point.GeneralCurveRadius = Circumradius3D(ARS.RouteNodes[Wrap(point.Node - 10, nodeCount)], ARS.RouteNodes[Wrap(point.Node + 10, nodeCount)], ARS.RouteNodes[point.Node]);
                    point.PreciseCurveRadius = Circumradius3D(ARS.RouteNodes[Wrap(point.Node - 4, nodeCount)], ARS.RouteNodes[Wrap(point.Node + 4, nodeCount)], ARS.RouteNodes[point.Node]);
                }
                else
                {
                    point.Angle = 0f;
                    point.Direction = (ARS.RouteNodes[10] - ARS.RouteNodes[5]).Normalized;
                    point.Elevation = 0f;
                }

                if (ARS.NodeHalfWidths.ContainsKey(point.Node)) point.TrackHalfWidth = ARS.NodeHalfWidths[point.Node];
            }

            BuildApexTable();
            ARS.Log(ARS.LogImportance.Info, "Route generated");
        }

        public static void BuildApexTable()
        {
            ARS.Corners.Clear();
            int count = ARS.TrackPoints.Count;
            if (count < 1) return;

            const float entryRadius = 100f;
            const float exitRadius = 130f;
            const int smoothingNodes = 2;
            const int exitRelaxationNodes = 4;
            const int minimumCornerNodes = 5;

            // Start a circuit scan on a straight so a corner crossing the node-zero boundary
            // is detected as one region rather than split between the end and beginning.
            int scanStart = 0;
            if (!ARS.IsPointToPoint)
            {
                for (int node = 0; node < count; node++)
                {
                    if (SmoothedRadius(node, count, smoothingNodes) >= exitRadius)
                    {
                        scanStart = node;
                        break;
                    }
                }
            }

            List<int> scanNodes = new List<int>(count);
            for (int offset = 0; offset < count; offset++)
            {
                int node = ARS.IsPointToPoint
                    ? scanStart + offset
                    : Wrap(scanStart + offset, count);
                if (node >= 0 && node < count) scanNodes.Add(node);
            }

            bool inCorner = false;
            int cornerStartPosition = -1;
            int cornerDirection = 0;
            int relaxedNodes = 0;

            for (int position = 0; position < scanNodes.Count; position++)
            {
                int node = scanNodes[position];
                float radius = SmoothedRadius(node, count, smoothingNodes);
                float generalRadius = ARS.TrackPoints[node].GeneralCurveRadius;
                int direction = Math.Sign(ARS.TrackPoints[node].Angle);
                bool cornerSignal = radius < entryRadius && generalRadius < exitRadius;

                if (!inCorner)
                {
                    if (cornerSignal && direction != 0)
                    {
                        inCorner = true;
                        cornerStartPosition = position;
                        cornerDirection = direction;
                        relaxedNodes = 0;
                    }
                    continue;
                }

                if (direction != 0 && direction != cornerDirection && cornerSignal)
                {
                    AddCornerRegion(scanNodes, cornerStartPosition, position - 1, count, smoothingNodes, minimumCornerNodes);
                    cornerStartPosition = position;
                    cornerDirection = direction;
                    relaxedNodes = 0;
                    continue;
                }

                if (!cornerSignal || radius >= exitRadius || direction == 0)
                    relaxedNodes++;
                else
                    relaxedNodes = 0;

                if (relaxedNodes >= exitRelaxationNodes)
                {
                    AddCornerRegion(scanNodes, cornerStartPosition, position - relaxedNodes, count, smoothingNodes, minimumCornerNodes);
                    inCorner = false;
                    cornerStartPosition = -1;
                    cornerDirection = 0;
                    relaxedNodes = 0;
                }
            }

            if (inCorner)
                AddCornerRegion(scanNodes, cornerStartPosition, scanNodes.Count - 1, count, smoothingNodes, minimumCornerNodes);

            ARS.Log(ARS.LogImportance.Info, "Apex table: " + ARS.Corners.Count + " corners");
        }

        static void AddCornerRegion(List<int> scanNodes, int startPosition, int endPosition, int count, int smoothingNodes, int minimumCornerNodes)
        {
            if (startPosition < 0 || endPosition < startPosition || endPosition - startPosition + 1 < minimumCornerNodes)
                return;

            int apexPosition = startPosition;
            float apexRadius = float.MaxValue;
            for (int position = startPosition; position <= endPosition; position++)
            {
                // The apex radius remains the precise node radius: circumradius through
                // the node and its +/-4-node samples. Smoothing is only for region detection.
                float radius = ARS.TrackPoints[scanNodes[position]].PreciseCurveRadius;
                if (radius < apexRadius)
                {
                    apexRadius = radius;
                    apexPosition = position;
                }
            }

            if (apexRadius >= 100f || float.IsNaN(apexRadius) || float.IsInfinity(apexRadius)) return;

            float entranceRadiusTarget = apexRadius * 2f;
            for (int position = startPosition; position < apexPosition; position++)
            {
                float radius = ARS.TrackPoints[scanNodes[position]].PreciseCurveRadius;
                if (radius < entranceRadiusTarget)
                {
                    startPosition = position;
                    break;
                }
            }

            int apexNode = scanNodes[apexPosition];
            ARS.Corners.Add(new CornerPoint
            {
                Node = apexNode,
                Angle = ARS.TrackPoints[apexNode].Angle,
                StartNode = scanNodes[startPosition],
                EndNode = scanNodes[endPosition],
                LengthStart = apexPosition - startPosition,
                LengthEnd = endPosition - apexPosition,
                SupposedRadius = apexRadius,
                Speed = (float)Math.Sqrt(9.81f * apexRadius)
            });
        }

        static float SmoothedRadius(int node, int count, int halfWindow)
        {
            float curvature = 0f;
            int samples = 0;
            for (int offset = -halfWindow; offset <= halfWindow; offset++)
            {
                int sample = ARS.IsPointToPoint
                    ? node + offset
                    : Wrap(node + offset, count);
                if (sample < 0 || sample >= count) continue;

                float radius = ARS.TrackPoints[sample].PreciseCurveRadius;
                if (radius <= 0f || radius >= 999f || float.IsNaN(radius) || float.IsInfinity(radius)) continue;
                curvature += 1f / radius;
                samples++;
            }

            return samples > 0 ? 1f / (curvature / samples) : 999f;
        }

        public static float Circumradius3D(Vector3 a, Vector3 b, Vector3 midpoint)
        {
            return Circumradius2D(new Vector2(a.X, a.Y), new Vector2(b.X, b.Y), new Vector2(midpoint.X, midpoint.Y));
        }

        public static float Circumradius2D(Vector2 a, Vector2 b, Vector2 midpoint)
        {
            Vector2 midpoint1 = (a + b) / 2;
            float dx1 = b.X - a.X;
            float slope1 = dx1 != 0f ? (b.Y - a.Y) / dx1 : float.PositiveInfinity;
            float perpendicular1 = slope1 != 0f ? -1 / slope1 : float.PositiveInfinity;
            Vector2 midpoint2 = (b + midpoint) / 2;
            float dx2 = midpoint.X - b.X;
            float slope2 = dx2 != 0f ? (midpoint.Y - b.Y) / dx2 : float.PositiveInfinity;
            float perpendicular2 = slope2 != 0f ? -1 / slope2 : float.PositiveInfinity;
            float denominator = perpendicular2 - perpendicular1;
            if (denominator == 0f || float.IsNaN(denominator) || float.IsInfinity(denominator)) return 999f;
            float centerX = (midpoint1.Y - midpoint2.Y + perpendicular2 * midpoint2.X - perpendicular1 * midpoint1.X) / denominator;
            float centerY = midpoint1.Y + perpendicular1 * (centerX - midpoint1.X);
            float radius = Vector2.Distance(new Vector2(centerX, centerY), a);
            return float.IsNaN(radius) || float.IsInfinity(radius) ? 999f : radius;
        }

        public static void InstanceTrack(ARS ars)
        {
            ars.CleanRacers();
            ars._gridInstanced = false;

            string trackPath = ars._selectedTrackPath;
            if (trackPath == null)
            {
                if (ARS.FilteredTracks.Count == 0)
                {
                    UI.Notify("~r~No tracks found. Create one with 'arscreatetrack'.");
                    return;
                }
                trackPath = ARS.FilteredTracks[0];
            }

            LoadTrack(ars, LoadTrackFile(trackPath));

            if (!ars._freeCam.IsActive) Function.Call(Hash.DO_SCREEN_FADE_IN, 500);

            ars._trackInstanced = true;
            ARS.Log(ARS.LogImportance.Info, "Track instanced");
        }

        public static void DiscoverTracks(ARS ars, bool allowScriptYield = true)
        {
            ars._trackTags.Clear();
            ARS.ImmersiveJoins.Clear();
            ARS.Log(ARS.LogImportance.Info, "Learning available tracks...");
            List<string> folders = Directory.GetDirectories(ARS.ScriptsFolder + @"\Tracks").ToList();
            folders.Add(ARS.ScriptsFolder + @"\Tracks");
            foreach (string dir in folders)
            {
                int count = 0;
                foreach (string st in Directory.EnumerateFiles(dir))
                {
                    string n = Path.GetFileName(st);
                    ARS.Log(ARS.LogImportance.Info, st + " - [" + string.Join(", ", TrackRepository.ReadTrackTags(st)) + "]");
                    ars._trackTags.Add(st, string.Join(", ", TrackRepository.ReadTrackTags(st)));
                    if (!ARS.ImmersiveJoins.ContainsKey(TrackRepository.ReadTrackStartPosition(st))) ARS.ImmersiveJoins.Add(TrackRepository.ReadTrackStartPosition(st), st);

                    count++;
                    if (allowScriptYield && count > 5)
                    {
                        ARS.DisplayHelpTextTimed("Loading " + n, 5000);
                        count = 0;
                        Script.Yield();
                    }
                }
            }

            ARS.KnownTracks = Directory.GetFiles(ARS.ScriptsFolder + @"\Tracks").ToList();
            ARS.Log(ARS.LogImportance.Info, "Done.");
            ARS.Log(ARS.LogImportance.Info, "-------------");
        }

        public static void FilterKnownTracks(ARS ars, string filter = "test")
        {
            ARS.FilteredTracks.Clear();
            string[] tags = filter.ToLowerInvariant().Split(' ');
            foreach (string file in ars._trackTags.Keys)
            {
                int score = 0;
                foreach (string tag in tags)
                {
                    if (ars._trackTags[file].Contains(tag)) score++;
                }
                if (score == tags.Length) ARS.FilteredTracks.Add(file);
            }
        }

        static int Wrap(int index, int count)
        {
            int wrapped = index % count;
            return wrapped < 0 ? wrapped + count : wrapped;
        }

        public static bool BuildTrackLimits(List<Vector3> nodes, Dictionary<int, float> widths, XmlDocument trackFile, bool isPointToPoint, int opponents, List<Prop> trackLimits, List<int> flareEffects, List<Vector3> gridPositions)
        {
            gridPositions.Clear();
            if (nodes.Count == 0) return isPointToPoint;
            isPointToPoint |= nodes[0].DistanceTo(nodes[nodes.Count - 1]) > 20f;
            Color flareColor = ReadFlareColor(trackFile);

            if (trackLimits.Count == 0) SpawnStartGates(nodes, widths, isPointToPoint, opponents, trackLimits, flareEffects, flareColor);
            if (isPointToPoint) BuildPointToPointGrid(nodes, widths, gridPositions);
            else BuildCircuitGrid(nodes, widths, gridPositions);
            Function.Call(Hash.CLEAR_FOCUS);
            return isPointToPoint;
        }

        static void SpawnStartGates(List<Vector3> nodes, Dictionary<int, float> widths, bool isPointToPoint, int opponents, List<Prop> limits, List<int> effects, Color color)
        {
            Vector3 start = isPointToPoint ? nodes[8 + opponents * 3] : nodes[0];
            SpawnGatePair(start, nodes[1] - nodes[0], widths[0], limits, effects, color);
            if (isPointToPoint) SpawnGatePair(nodes.Last(), nodes[nodes.Count - 2] - nodes.Last(), widths[0], limits, effects, color);
        }

        static void SpawnGatePair(Vector3 position, Vector3 direction, float width, List<Prop> limits, List<int> effects, Color color)
        {
            for (int side = -1; side <= 1; side += 2)
            {
                Prop gate = World.CreateProp("prop_flare_01b", position + new Vector3(0f, 0f, 0.05f), new Vector3(0, 0, direction.Normalized.ToHeading() + 90f), false, false);
                gate.Position += gate.RightVector * width * side;
                AttachFlare(gate, color, effects);
                gate.FreezePosition = true;
                gate.HasCollision = false;
                limits.Add(gate);
            }
        }

        static void BuildPointToPointGrid(List<Vector3> nodes, Dictionary<int, float> widths, List<Vector3> grid)
        {
            for (int i = 50; i > 1; i--)
            {
                Vector3 point = nodes[i * 3];
                Vector3 direction = (point - nodes[i * 3 - 1]).Normalized;
                grid.Add(point - Quaternion.RotationAxis(Vector3.WorldUp, (float)Math.PI / 180f * -90f) * (direction * ((i % 2 == 1) ? widths[0] * 0.45f : -widths[0] * 0.45f)));
            }
        }

        static void BuildCircuitGrid(List<Vector3> nodes, Dictionary<int, float> widths, List<Vector3> grid)
        {
            int reference = nodes.Count - 1;
            for (int i = nodes.Count - 1; i > 50 && grid.Count <= 40; i--)
            {
                if (i >= reference - 5) continue;
                Vector3 direction = (nodes[reference] - nodes[i]).Normalized;
                grid.Add(nodes[i] - Quaternion.RotationAxis(Vector3.WorldUp, (float)Math.PI / 180f * -90f) * (direction * ((grid.Count % 2 == 1) ? -widths[0] * 0.45f : widths[0] * 0.45f)));
                reference = i;
            }
        }

        static Color ReadFlareColor(XmlDocument trackFile)
        {
            string value = trackFile?.SelectSingleNode("//Trackside") is XmlElement element ? element.GetAttribute("Flares") : "";
            int rgb;
            return value.Length == 9 && int.TryParse(value, out rgb) ? Color.FromArgb(int.Parse(value.Substring(0, 3)), int.Parse(value.Substring(3, 3)), int.Parse(value.Substring(6, 3))) : Color.GreenYellow;
        }

        static void AttachFlare(Prop prop, Color color, List<int> effects)
        {
            int tries = 0;
            while (!Function.Call<bool>(Hash.HAS_NAMED_PTFX_ASSET_LOADED, "scr_apartment_mp") && tries++ < 2000) Function.Call(Hash.REQUEST_NAMED_PTFX_ASSET, "scr_apartment_mp");
            if (!Function.Call<bool>(Hash.HAS_NAMED_PTFX_ASSET_LOADED, "scr_apartment_mp")) return;
            Function.Call(Hash._SET_PTFX_ASSET_NEXT_CALL, "scr_apartment_mp");
            int effect = Function.Call<int>(Hash.START_PARTICLE_FX_LOOPED_ON_ENTITY, "scr_finders_package_flare", prop, 0f, 0f, 0.1f, 0f, 0f, 0f, 1f, true, true, true);
            Function.Call(Hash.SET_PARTICLE_FX_LOOPED_ALPHA, effect, 1f);
            Function.Call(Hash.SET_PARTICLE_FX_LOOPED_COLOUR, effect, color.R / 255f, color.G / 255f, color.B / 255f, 1f, true);
            effects.Add(effect);
        }
    }
}
