using GTA;
using GTA.Math;
using GTA.Native;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;
using System.Xml;

namespace ARS
{
    public static class TrackLoader
    {
        public static XmlDocument LoadTrackFile(string trackname = null)
        {
            ARS.Log(ARS.LogImportance.Info, "Loading " + trackname);
            return TrackRepository.Load(trackname);
        }

        public static void LoadTrack(ARS ars, XmlDocument xmlFile)
        {
            ARS.Log(ARS.LogImportance.Info, "Loading track");
            if (xmlFile == null)
            {
                UI.Notify("~r~Invalid track file.");
                return;
            }
            if (!ars._freeCam.IsActive) Function.Call(Hash.DO_SCREEN_FADE_OUT, 200);
            ars.SetLoadingPromptText("Loading track...");
            Script.Wait(500);

            ARS.CurrentFile = xmlFile;
            foreach (Prop p in ARS.CustomProps) if (ARS.CanWeUse(p)) p.Delete();
            foreach (Prop p in ARS.AutoGeneratedProps) if (ARS.CanWeUse(p)) p.Delete();
            foreach (Prop p in ARS.TrackLimits) if (ARS.CanWeUse(p)) p.Delete();
            ARS.Angles.Clear();
            ARS.RouteNodes.Clear();
            ARS.NodeHalfWidths.Clear();
            ARS.TrackLimits.Clear();

            XmlNode r = xmlFile.SelectSingleNode("Data");

            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");

            foreach (XmlElement prop in r.SelectNodes("Objects/Prop"))
            {
                string x = "0";
                string y = "0";
                string z = "0";
                if (ARS.NodeExists(prop, "X") && ARS.NodeExists(prop, "Y") && ARS.NodeExists(prop, "Z"))
                {
                    x = prop.SelectSingleNode("X").InnerText;
                    y = prop.SelectSingleNode("Y").InnerText;
                    z = prop.SelectSingleNode("Z").InnerText;
                }

                bool isDynamic = false;

                if (ARS.NodeExists(prop, "IsDynamic")) bool.TryParse(prop.SelectSingleNode("IsDynamic").InnerText, out isDynamic);

                float fx = 0f;
                float.TryParse(x, out fx);
                float fy = 0f;
                float.TryParse(y, out fy);
                float fz = 0f;
                float.TryParse(z, out fz);
                Vector3 pos = new Vector3(fx, fy, fz);
                if (ARS.NodeExists(prop, "RotX") && ARS.NodeExists(prop, "RotY") && ARS.NodeExists(prop, "RotZ"))
                {
                    x = prop.SelectSingleNode("RotX").InnerText;
                    y = prop.SelectSingleNode("RotY").InnerText;
                    z = prop.SelectSingleNode("RotZ").InnerText;
                }
                fx = 0f;
                float.TryParse(x, out fx);
                fy = 0f;
                float.TryParse(y, out fy);
                fz = 0f;
                float.TryParse(z, out fz);
                Vector3 rot = new Vector3(fx, fy, fz);

                if (ARS.NodeExists(prop, "Model"))
                {
                    int hash = 0;
                    int.TryParse(prop.SelectSingleNode("Model").InnerText, out hash);
                    if (hash != 0 && new Model(hash).IsValid)
                    {
                        Prop myprop = World.CreateProp(hash, pos, rot, false, false);
                        myprop.Position = pos;
                        Function.Call(Hash.SET_ENTITY_DYNAMIC, myprop, isDynamic);
                        Function.Call(Hash.FREEZE_ENTITY_POSITION, myprop, !isDynamic);
                        Function.Call(Hash.SET_OBJECT_PHYSICS_PARAMS, myprop, 200f * myprop.Model.GetDimensions().Length(), 1f);

                        if (prop.SelectSingleNode("TextureVariation") != null) Function.Call(Hash._0x971DA0055324D033, myprop, int.Parse(prop.SelectSingleNode("TextureVariation").InnerText));

                        ARS.CustomProps.Add(myprop);
                    }
                }
            }
            List<XmlElement> routeNodes = new List<XmlElement>();
            foreach (XmlElement e in r.SelectNodes("Route/Point")) routeNodes.Add(e);

            if (ARS.DebugToggles[Options.ReverseRoute])
            {
                routeNodes.Reverse();
                UI.Notify("~g~Route is reversed.");
            }

            int i = 0;
            float W = 5;
            float oldW = 0;
            foreach (XmlElement e in routeNodes)
            {
                string x = e.SelectSingleNode("X").InnerText;
                string y = e.SelectSingleNode("Y").InnerText;
                string z = e.SelectSingleNode("Z").InnerText;

                float fx = 0f;
                float.TryParse(x, out fx);
                float fy = 0f;
                float.TryParse(y, out fy);
                float fz = 0f;
                float.TryParse(z, out fz);
                Vector3 pos = new Vector3(fx, fy, fz);

                float.TryParse(e.SelectSingleNode("Wide").InnerText, out W);

                if (ARS.RouteNodes.Count > 5) W = ARS.Clamp(W, oldW - 0.25f, oldW + 0.25f);

                if (e.SelectSingleNode("RacingLine") != null && ARS.SettingsFile.GetValue<bool>("GENERAL_SETTINGS", "ReverseRoutes", false) == false)
                {
                    float racingline = 0.0f;
                    float.TryParse(e.SelectSingleNode("RacingLine").InnerText, out racingline);
                }

                ARS.RouteNodes.Add(pos);
                ARS.NodeHalfWidths.Add(i, W);
                oldW = W;
                i++;
            }

            // Detect circuit vs point-to-point BEFORE GenerateRouteInfo so the geometry pass
            // (Angle/Direction/Elevation/PreciseCurveRadius) and BuildApexCorners can wrap node
            // indices across the start/finish seam. Without this, corners sitting on the finish
            // line are invisible to the apex table on circuits.
            ARS.IsPointToPoint = false;
            if (ARS.RouteNodes[0].DistanceTo(ARS.RouteNodes[ARS.RouteNodes.Count - 1]) > 20) ARS.IsPointToPoint = true;

            RouteAnalysis.Generate();

            Script.Wait(1000);
            ARS.Log(ARS.LogImportance.Info, "Loading props");
            ars.SetLoadingPromptText("Loading props...");
            ars.SpawnTrackLimits(ARS.RouteNodes, ARS.NodeHalfWidths, 1);

            if (ARS.CanWeUse(Game.Player.Character.CurrentVehicle)) Game.Player.Character.CurrentVehicle.Position = ARS.RouteNodes[0]; else Game.Player.Character.Position = ARS.RouteNodes[20];
            if (ARS.CanWeUse(ARS.FreeCamRide)) ARS.FreeCamRide.Position = ARS.RouteNodes[5] + new Vector3(0, 0, 20);
            ars.SetLoadingPromptText("Finished loading props");
            Function.Call(Hash._0x10D373323E5B9C0D);
            ars.SetSPLVisibility(false);

            ARS.Log(ARS.LogImportance.Info, "Loaded track");
        }
    }
}
