using GTA;
using GTA.Math;
using GTA.Native;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Xml;

namespace ARS
{
    public static class TrackLoader
    {
        public static XmlDocument LoadTrackFile(string trackname = null)
        {
            ARS.Log(ARS.LogImportance.Info, "Loading " + trackname);
            return TrackRepository.Load(trackname);
        }

        public static void LoadTrack(ARS ars, XmlDocument xmlFile)
        {
            ARS.Log(ARS.LogImportance.Info, "Loading track");
            if (xmlFile == null)
            {
                UI.Notify("~r~Invalid track file.");
                return;
            }
            if (!ars.IsFreeCamActive) Function.Call(Hash.DO_SCREEN_FADE_OUT, 200);
            ars.SetLoadingPromptText("Loading track...");
            Script.Wait(500);

            ARS.CurrentFile = xmlFile;
            foreach (Prop p in ARS.CustomProps) if (ARS.CanWeUse(p)) p.Delete();
            foreach (Prop p in ARS.AutoGeneratedProps) if (ARS.CanWeUse(p)) p.Delete();
            foreach (Prop p in ARS.StartLineFlares) if (ARS.CanWeUse(p)) p.Delete();
            ARS.Angles.Clear();
            ARS.RouteNodes.Clear();
            ARS.NodeHalfWidths.Clear();
            ARS.StartLineFlares.Clear();
            QueuedFlares.Clear();

            XmlNode r = xmlFile.SelectSingleNode("Data");

            Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo("en-US");

            foreach (XmlElement prop in r.SelectNodes("Objects/Prop"))
            {
                string x = "0";
                string y = "0";
                string z = "0";
                if (ARS.NodeExists(prop, "X") && ARS.NodeExists(prop, "Y") && ARS.NodeExists(prop, "Z"))
                {
                    x = prop.SelectSingleNode("X").InnerText;
                    y = prop.SelectSingleNode("Y").InnerText;
                    z = prop.SelectSingleNode("Z").InnerText;
                }

                bool isDynamic = false;

                if (ARS.NodeExists(prop, "IsDynamic")) bool.TryParse(prop.SelectSingleNode("IsDynamic").InnerText, out isDynamic);

                float fx = 0f;
                float.TryParse(x, out fx);
                float fy = 0f;
                float.TryParse(y, out fy);
                float fz = 0f;
                float.TryParse(z, out fz);
                Vector3 pos = new Vector3(fx, fy, fz);
                if (ARS.NodeExists(prop, "RotX") && ARS.NodeExists(prop, "RotY") && ARS.NodeExists(prop, "RotZ"))
                {
                    x = prop.SelectSingleNode("RotX").InnerText;
                    y = prop.SelectSingleNode("RotY").InnerText;
                    z = prop.SelectSingleNode("RotZ").InnerText;
                }
                fx = 0f;
                float.TryParse(x, out fx);
                fy = 0f;
                float.TryParse(y, out fy);
                fz = 0f;
                float.TryParse(z, out fz);
                Vector3 rot = new Vector3(fx, fy, fz);

                if (ARS.NodeExists(prop, "Model"))
                {
                    int hash = 0;
                    int.TryParse(prop.SelectSingleNode("Model").InnerText, out hash);
                    if (hash != 0 && new Model(hash).IsValid)
                    {
                        Prop myprop = World.CreateProp(hash, pos, rot, false, false);
                        myprop.Position = pos;
                        Function.Call(Hash.SET_ENTITY_DYNAMIC, myprop, isDynamic);
                        Function.Call(Hash.FREEZE_ENTITY_POSITION, myprop, !isDynamic);
                        Function.Call(Hash.SET_OBJECT_PHYSICS_PARAMS, myprop, 200f * myprop.Model.GetDimensions().Length(), 1f);

                        if (prop.SelectSingleNode("TextureVariation") != null) Function.Call(Hash._0x971DA0055324D033, myprop, int.Parse(prop.SelectSingleNode("TextureVariation").InnerText));

                        ARS.CustomProps.Add(myprop);
                    }
                }
            }
            List<XmlElement> routeNodes = new List<XmlElement>();
            foreach (XmlElement e in r.SelectNodes("Route/Point")) routeNodes.Add(e);

            if (ARS.DebugToggles[Options.ReverseRoute])
            {
                routeNodes.Reverse();
            }

            int i = 0;
            float W = 5;
            float oldW = 0;
            foreach (XmlElement e in routeNodes)
            {
                string x = e.SelectSingleNode("X").InnerText;
                string y = e.SelectSingleNode("Y").InnerText;
                string z = e.SelectSingleNode("Z").InnerText;

                float fx = 0f;
                float.TryParse(x, out fx);
                float fy = 0f;
                float.TryParse(y, out fy);
                float fz = 0f;
                float.TryParse(z, out fz);
                Vector3 pos = new Vector3(fx, fy, fz);

                float.TryParse(e.SelectSingleNode("Wide").InnerText, out W);

                if (ARS.RouteNodes.Count > 5) W = ARS.Clamp(W, oldW - 0.25f, oldW + 0.25f);

                ARS.RouteNodes.Add(pos);
                ARS.NodeHalfWidths.Add(i, W);
                oldW = W;
                i++;
            }

            // Detect circuit vs point-to-point BEFORE GenerateRouteInfo so the geometry pass and BuildApexTable can
            // wrap node indices across the start/finish seam; without it, a corner sitting on the finish line is
            // invisible to the apex table on circuits.
            ARS.IsPointToPoint = false;
            if (ARS.RouteNodes[0].DistanceTo(ARS.RouteNodes[ARS.RouteNodes.Count - 1]) > 20) ARS.IsPointToPoint = true;

            GenerateRouteInfo();

            Script.Wait(1000);
            ARS.Log(ARS.LogImportance.Info, "Loading props");
            ars.SetLoadingPromptText("Loading props...");
            BuildTrackLimits(ARS.RouteNodes, ARS.NodeHalfWidths, ARS.CurrentFile, ref ARS.IsPointToPoint, ARS.StartLineFlares);

            if (ARS.CanWeUse(Game.Player.Character.CurrentVehicle))
            {
                Game.Player.Character.CurrentVehicle.Position = ARS.RouteNodes[0];
            }
            else
            {
                Vector3 pos = ARS.RouteNodes[2];
                Vector3 dir = ARS.RouteNodes[3] - ARS.RouteNodes[1];
                dir.Z = 0f;
                if (dir.LengthSquared() < 0.001f) dir = Vector3.WorldNorth;
                dir.Normalize();
                Vector3 right = Vector3.Cross(dir, Vector3.WorldUp);
                float halfWide = ARS.NodeHalfWidths.ContainsKey(2) ? ARS.NodeHalfWidths[2] : 5f;
                float side = ARS.GetRandomInt(0, 2) == 0 ? 1f : -1f;
                Game.Player.Character.Position = pos + right * (halfWide * side) + new Vector3(0f, 0f, 0.5f);
            }
            if (ARS.CanWeUse(ARS.FreeCamRide)) ARS.FreeCamRide.Position = ARS.RouteNodes[5] + new Vector3(0, 0, 20);
            ars.SetLoadingPromptText("Finished loading props");
            Function.Call(Hash._0x10D373323E5B9C0D);
            ars.SetSPLVisibility(false);

            ARS.Log(ARS.LogImportance.Info, "Loaded track");
        }

        public static void GenerateRouteInfo()
        {
            ARS.Log(ARS.LogImportance.Info, "Generating route info...");
            ARS.TrackPoints.Clear();
            while (ARS.TrackPoints.Count < ARS.RouteNodes.Count)
            {
                int node = ARS.TrackPoints.Count;
                ARS.TrackPoints.Add(new TrackPoint { Node = node, Position = ARS.RouteNodes[node] });
            }

            float cumulative = 0f;
            for (int i = 0; i < ARS.TrackPoints.Count; i++)
            {
                ARS.TrackPoints[i].CumulativeDistance = cumulative;
                int next = (i + 1) % ARS.TrackPoints.Count;
                cumulative += ARS.TrackPoints[i].Position.DistanceTo(ARS.TrackPoints[next].Position);
            }

            int nodeCount = ARS.RouteNodes.Count;
            foreach (TrackPoint point in ARS.TrackPoints)
            {
                int average = (int)(point.TrackHalfWidth * 2);
                bool canCompute = ARS.IsPointToPoint
                    ? point.Node > 50 && point.Node < nodeCount - 50
                    : point.Node >= 0 && point.Node < nodeCount;

                if (canCompute)
                {
                    Vector3 left = (ARS.RouteNodes[point.Node] - ARS.RouteNodes[Wrap(point.Node - average, nodeCount)]).Normalized;
                    Vector3 forward = (ARS.RouteNodes[Wrap(point.Node + average, nodeCount)] - ARS.RouteNodes[point.Node]).Normalized;
                    point.Direction = (ARS.RouteNodes[Wrap(point.Node + 2, nodeCount)] - ARS.RouteNodes[Wrap(point.Node - 2, nodeCount)]).Normalized;
                    point.Elevation = (ARS.RouteNodes[Wrap(point.Node + 3, nodeCount)] - ARS.RouteNodes[Wrap(point.Node - 3, nodeCount)]).Normalized.Z * 90f;
                    left.Z = 0f;
                    forward.Z = 0f;
                    point.Angle = Vector3.SignedAngle(left, forward, Vector3.WorldUp);
                    if (float.IsNaN(point.Angle) || float.IsInfinity(point.Angle)) point.Angle = 0f;
                    point.GeneralCurveRadius = Circumradius3D(ARS.RouteNodes[Wrap(point.Node - 10, nodeCount)], ARS.RouteNodes[Wrap(point.Node + 10, nodeCount)], ARS.RouteNodes[point.Node]);
                    point.PreciseCurveRadius = Circumradius3D(ARS.RouteNodes[Wrap(point.Node - 4, nodeCount)], ARS.RouteNodes[Wrap(point.Node + 4, nodeCount)], ARS.RouteNodes[point.Node]);
                    point.ExactRadius = Circumradius3D(ARS.RouteNodes[Wrap(point.Node - 2, nodeCount)], ARS.RouteNodes[Wrap(point.Node + 2, nodeCount)], ARS.RouteNodes[point.Node]);
                }
                else
                {
                    point.Angle = 0f;
                    point.Direction = (ARS.RouteNodes[10] - ARS.RouteNodes[5]).Normalized;
                    point.Elevation = 0f;
                }

                if (ARS.NodeHalfWidths.ContainsKey(point.Node)) point.TrackHalfWidth = ARS.NodeHalfWidths[point.Node];
            }

            BuildApexTable();
            ARS.Log(ARS.LogImportance.Info, "Route generated");
        }

        public static void BuildApexTable()
        {
            ARS.Corners.Clear();
            int count = ARS.TrackPoints.Count;
            if (count < 1) return;

            const float entryRadius = 200f;
            const float exitRadius = 200f;
            const int smoothingNodes = 2;
            const int exitRelaxationNodes = 4;
            const int minimumCornerNodes = 25;
            const float closeCornerSeconds = 2f;

            // Start a circuit scan on a straight so a corner crossing the node-zero boundary
            // is detected as one region rather than split between the end and beginning.
            int scanStart = 0;
            if (!ARS.IsPointToPoint)
            {
                for (int node = 0; node < count; node++)
                {
                    if (SmoothedRadius(node, count, smoothingNodes) >= exitRadius)
                    {
                        scanStart = node;
                        break;
                    }
                }
            }

            List<int> scanNodes = new List<int>(count);
            for (int offset = 0; offset < count; offset++)
            {
                int node = ARS.IsPointToPoint
                    ? scanStart + offset
                    : Wrap(scanStart + offset, count);
                if (node >= 0 && node < count) scanNodes.Add(node);
            }

            bool inCorner = false;
            int cornerStartPosition = -1;
            int cornerDirection = 0;
            int relaxedNodes = 0;

            for (int position = 0; position < scanNodes.Count; position++)
            {
                int node = scanNodes[position];
                float radius = SmoothedRadius(node, count, smoothingNodes);
                float generalRadius = ARS.TrackPoints[node].GeneralCurveRadius;
                int direction = Math.Sign(ARS.TrackPoints[node].Angle);
                bool cornerSignal = radius < entryRadius && generalRadius < exitRadius;

                if (!inCorner)
                {
                    if (cornerSignal && direction != 0)
                    {
                        inCorner = true;
                        cornerStartPosition = position;
                        cornerDirection = direction;
                        relaxedNodes = 0;
                    }
                    continue;
                }

                if (direction != 0 && direction != cornerDirection && cornerSignal)
                {
                    AddCornerRegion(scanNodes, cornerStartPosition, position - 1, count, smoothingNodes, minimumCornerNodes, closeCornerSeconds);
                    cornerStartPosition = position;
                    cornerDirection = direction;
                    relaxedNodes = 0;
                    continue;
                }

                if (!cornerSignal || radius >= exitRadius || direction == 0)
                    relaxedNodes++;
                else
                    relaxedNodes = 0;

                if (relaxedNodes >= exitRelaxationNodes)
                {
                    AddCornerRegion(scanNodes, cornerStartPosition, position - relaxedNodes, count, smoothingNodes, minimumCornerNodes, closeCornerSeconds);
                    inCorner = false;
                    cornerStartPosition = -1;
                    cornerDirection = 0;
                    relaxedNodes = 0;
                }
            }

            if (inCorner)
                AddCornerRegion(scanNodes, cornerStartPosition, scanNodes.Count - 1, count, smoothingNodes, minimumCornerNodes, closeCornerSeconds);

            float widestApexRadius = 0f;
            foreach (CornerPoint counted in ARS.Corners) widestApexRadius = Math.Max(widestApexRadius, counted.SupposedRadius);
            ARS.Log(ARS.LogImportance.Info, "Apex table: " + ARS.Corners.Count + " corners, widest apex radius " + widestApexRadius.ToString("0") + "m");

            // A chicane turns the heading back on itself, so the headings either side of the apex lie on the same
            // side of the apex direction and the signed angles match. A single corner keeps turning, so they differ.
            int nodeCount = ARS.TrackPoints.Count;
            for (int i = 0; i < ARS.Corners.Count; i++)
            {
                CornerPoint corner = ARS.Corners[i];
                int apex = corner.Node;
                int walkDist = (int)(ARS.TrackPoints[apex].TrackHalfWidth * 4f); // full width × 2
                Vector3 apexDir = ARS.TrackPoints[apex].Direction;

                int backNode = apex - walkDist;
                if (!ARS.IsPointToPoint) backNode = ((backNode % nodeCount) + nodeCount) % nodeCount;
                if (backNode < 0 || backNode >= nodeCount) continue;

                int fwdNode = apex + walkDist;
                if (!ARS.IsPointToPoint) fwdNode = fwdNode % nodeCount;
                if (fwdNode < 0 || fwdNode >= nodeCount) continue;

                float angleBack = Vector3.SignedAngle(apexDir, ARS.TrackPoints[backNode].Direction, Vector3.WorldUp);
                float angleFwd = Vector3.SignedAngle(apexDir, ARS.TrackPoints[fwdNode].Direction, Vector3.WorldUp);

                if (Math.Abs(angleBack) > 1f && Math.Abs(angleFwd) > 1f && Math.Sign(angleBack) == Math.Sign(angleFwd))
                {
                    corner.IsChicane = true;
                }
            }

            AssignCrestNodes(nodeCount);

            ARS.CornersRevision++;
        }

        // A crest before a corner unloads the tyres exactly where the car wants to brake, so the braking plan must know
        // about it and the entrance moves back to its top. Scanned once here, after the merges, because every rule that
        // rewrites the entrance has to have settled first. The scan is deliberately boundary-free: a crest that belongs
        // to the previous corner is still crossed before this one, so the unload is real for this corner's plan -- only
        // the move below is bounded by the previous corner.
        static void AssignCrestNodes(int count)
        {
            const float probeSpeed = ARS.CrestProbeSpeed;
            const float threshold = 0.15f;
            const int window = 6;
            const int scanBack = 100;
            const int minRun = 3;

            foreach (CornerPoint corner in ARS.Corners)
            {
                corner.CrestNode = -1;
                corner.CrestGs = 0f;
                corner.CrestSpanNodes = 0;

                int entrance = corner.StartNode;
                int run = 0;
                int runPeak = -1;
                float runPeakGs = 0f;
                for (int back = 1; back <= scanBack; back++)
                {
                    int node = CrestNode(entrance - back, count);
                    int before = CrestNode(entrance - back - window, count);
                    int after = CrestNode(entrance - back + window, count);
                    if (node < 0 || before < 0 || after < 0) break;
                    float g = ARS.HillGripDeltaGs(ARS.TrackPoints[before].Position, ARS.TrackPoints[node].Position, ARS.TrackPoints[after].Position, probeSpeed);
                    if (g >= threshold) break;
                    if (g > -threshold)
                    {
                        if (run >= minRun) break;
                        run = 0;
                        runPeak = -1;
                        runPeakGs = 0f;
                        continue;
                    }
                    run++;
                    if (runPeak < 0 || g < runPeakGs)
                    {
                        runPeakGs = g;
                        runPeak = node;
                    }
                }
                if (run < minRun) continue;
                corner.CrestNode = runPeak;
                corner.CrestGs = runPeakGs;
                corner.CrestSpanNodes = CrestBaseWidth(runPeak, run, count);
            }

            int crests = 0;
            foreach (CornerPoint corner in ARS.Corners)
            {
                if (corner.CrestNode < 0) continue;
                crests++;
                ARS.Log(ARS.LogImportance.Info, "Crest " + crests + ": node=" + corner.CrestNode + " gs=" + corner.CrestGs.ToString("0.000") + " extent=" + corner.CrestSpanNodes + " from=" + corner.StartNode + " apex=" + corner.Node);
            }

            MoveEntrancesToCrests(count);

            ARS.Log(ARS.LogImportance.Info, "Crests: " + crests + " of " + ARS.Corners.Count + " corners carry one, threshold " + threshold.ToString("0.00") + "g at " + probeSpeed.ToString("0") + "m/s");
        }

        // The entrance walks back to the crest top, bounded so it never lands inside the previous corner. The EXIT binds
        // rather than the apex: the previous corner's region runs to its exit, and anchoring this corner's braking plan
        // inside that region demands this apex speed while the car is still at the previous corner's curvature, which
        // over-slows that exit and samples this plan across it. ExitStep walks forward, so the exit is past the apex.
        static void MoveEntrancesToCrests(int count)
        {
            const int moveMargin = 10;
            const int moveCap = 60;

            for (int i = 0; i < ARS.Corners.Count; i++)
            {
                CornerPoint corner = ARS.Corners[i];
                if (corner.CrestNode < 0) continue;
                int move = ARS.IsPointToPoint ? corner.StartNode - corner.CrestNode : Wrap(corner.StartNode - corner.CrestNode, count);
                string verdict = move < 1 ? "no move" : move > moveCap ? "over cap" : "applied";

                CornerPoint previous = i > 0 ? ARS.Corners[i - 1] : ARS.IsPointToPoint ? null : ARS.Corners[ARS.Corners.Count - 1];
                if (verdict == "applied" && previous != null)
                {
                    int toApex = ARS.IsPointToPoint ? corner.Node - previous.EndNode : Wrap(corner.Node - previous.EndNode, count);
                    int toCrest = ARS.IsPointToPoint ? corner.CrestNode - previous.EndNode : Wrap(corner.CrestNode - previous.EndNode, count);
                    if (toCrest < moveMargin) verdict = "inside previous margin";
                    else if (toCrest > toApex) verdict = "before previous exit";
                }

                if (verdict != "applied")
                {
                    ARS.Log(ARS.LogImportance.Info, "Crest move skipped: node=" + corner.CrestNode + " move=" + move + "m (" + verdict + ")");
                    continue;
                }

                corner.StartNode = corner.CrestNode;
                corner.LengthStart = ARS.IsPointToPoint ? corner.Node - corner.CrestNode : Wrap(corner.Node - corner.CrestNode, count);
            }
        }

        // The run is only the threshold-crossing width and the triangle reaches zero at the inflections, so using the run
        // as the extent would under-count the unload. Walks out to zero curvature from the peak, each side capped at the
        // run, so a shallow shoulder cannot inflate it. The two sides usually differ and the ramp is one scalar, so it
        // stays symmetric about the peak and averages that asymmetry rather than following it.
        static int CrestBaseWidth(int peak, int run, int count)
        {
            int limit = run;
            int left = 0;
            while (left < limit && CrestCurvature(peak - left - 1, count) < 0f) left++;
            int right = 0;
            while (right < limit && CrestCurvature(peak + right + 1, count) < 0f) right++;
            return left + right + 1;
        }

        static float CrestCurvature(int node, int count)
        {
            const float probeSpeed = ARS.CrestProbeSpeed;
            const int window = 6;
            int centre = CrestNode(node, count);
            int before = CrestNode(node - window, count);
            int after = CrestNode(node + window, count);
            if (centre < 0 || before < 0 || after < 0) return 0f;
            return ARS.HillGripDeltaGs(ARS.TrackPoints[before].Position, ARS.TrackPoints[centre].Position, ARS.TrackPoints[after].Position, probeSpeed);
        }

        static int CrestNode(int node, int count)
        {
            if (node < 0 || node >= count) return ARS.IsPointToPoint ? -1 : ((node % count) + count) % count;
            return node;
        }

        static void AddCornerRegion(List<int> scanNodes, int startPosition, int endPosition, int count, int smoothingNodes, int minimumCornerNodes, float closeCornerSeconds)
        {
            if (startPosition < 0 || endPosition < startPosition || endPosition - startPosition + 1 < minimumCornerNodes)
                return;

            int regionStart = startPosition;
            int regionEnd = endPosition;

            int apexPosition = startPosition;
            float apexRadius = float.MaxValue;
            float detectedRadius = float.MaxValue;
            for (int position = startPosition; position <= endPosition; position++)
            {
                // The apex radius remains the precise node radius: circumradius through
                // the node and its +/-4-node samples. Smoothing is only for region detection.
                float radius = ARS.TrackPoints[scanNodes[position]].PreciseCurveRadius;
                if (radius < apexRadius)
                {
                    apexRadius = radius;
                    apexPosition = position;
                }
                float smoothed = SmoothedRadius(scanNodes[position], count, smoothingNodes);
                if (smoothed < detectedRadius) detectedRadius = smoothed;
            }

            if (float.IsNaN(apexRadius) || float.IsInfinity(apexRadius)) return;
            // A wide region is a bend, not a corner: the apex reads the precise radius, which the region's smoothed
            // radius can sit well under, so a region does open without a tight node inside it.
            if (apexRadius > MaximumApexRadius) return;

            int apexNode = scanNodes[apexPosition];
            // A span is capped at a hard node count each way rather than by the corner's own size: offroad the radius
            // never settles, so without a cap the walk runs all the way out to the region bound. The step is also capped
            // by what the scan list holds, because the walk returns a step count and these are list positions.
            int spanLimit = Math.Min(SpanNodeLimit, count - 1);
            startPosition = apexPosition - EntranceStep(apexNode, Math.Min(spanLimit, apexPosition), count);
            endPosition = apexPosition + ExitStep(apexNode, Math.Min(spanLimit, scanNodes.Count - 1 - apexPosition), count);
            // Flat rather than the apex radius: scaling it gave a sweeper a span of twice its own radius, so the cars
            // prepared across the whole corner.
            float minEntranceExit = Math.Min(SpanMinimumMeters, spanLimit);
            if (apexPosition - startPosition < minEntranceExit) startPosition = Math.Max(regionStart, apexPosition - (int)minEntranceExit);
            if (endPosition - apexPosition < minEntranceExit) endPosition = Math.Min(regionEnd, apexPosition + (int)minEntranceExit);
            CornerPoint corner = new CornerPoint
            {
                Node = apexNode,
                Angle = ARS.TrackPoints[apexNode].Angle,
                StartNode = scanNodes[startPosition],
                EndNode = scanNodes[endPosition],
                LengthStart = apexPosition - startPosition,
                LengthEnd = endPosition - apexPosition,
                SupposedRadius = apexRadius,
                DetectedRadius = detectedRadius,
                Speed = (float)Math.Sqrt(9.81f * apexRadius)
            };

            // Coexistence is a question of time, not distance: the outside-approach window is a few seconds long, so
            // two apexes the car reaches within this many seconds fight over the same stretch. The table has no car
            // in it, so the corners' own 1 g apex speeds stand in — which is how the radius drives the decision.
            // Keeping the slower of the pair is deliberate, and the survivor's extensions are then re-walked over
            // the region it absorbed: leaving them alone registers no corner where the car actually is.
            if (ARS.Corners.Count > 0)
            {
                CornerPoint previous = ARS.Corners[ARS.Corners.Count - 1];
                int gap = ARS.IsPointToPoint ? corner.Node - previous.Node : Wrap(corner.Node - previous.Node, count);
                float referenceSpeed = Math.Max(previous.Speed, corner.Speed);
                float gapSeconds = gap / Math.Max(referenceSpeed, 1f);
                // A fast kink seconds before a slow corner is one the car clears before it can react to the next: where
                // the two aim the same way there is no S to drive, so the slower apex should own the whole bend. The
                // aligned case needs its own ceiling, or two similar corners half a lap apart would merge.
                bool sameBend = gapSeconds < AlignedCornerSeconds && AimsSameWay(previous, corner, AlignedCornerDegrees);
                if (gapSeconds < closeCornerSeconds || sameBend)
                {
                    CornerPoint survivor = corner.Speed < previous.Speed ? corner : previous;
                    ExtendMergedCorner(survivor, previous.StartNode, corner.EndNode, count);
                    ARS.Corners[ARS.Corners.Count - 1] = survivor;
                    return;
                }
            }
            ARS.Corners.Add(corner);
        }

        // Whether one corner's exit aims where the next one's entrance aims: joined by a straight or a steady curve, so
        // the pair is really one bend rather than an S.
        static bool AimsSameWay(CornerPoint previous, CornerPoint corner, float degrees)
        {
            if (previous.EndNode < 0 || corner.StartNode < 0) return false;
            Vector3 exitDirection = ARS.TrackPoints[previous.EndNode].Direction;
            Vector3 entranceDirection = ARS.TrackPoints[corner.StartNode].Direction;
            float angle = Vector3.SignedAngle(exitDirection, entranceDirection, Vector3.WorldUp);
            return !float.IsNaN(angle) && !float.IsInfinity(angle) && Math.Abs(angle) <= degrees;
        }

        // The entrance is the exit's mirror, walked back from the apex to the first node whose road holds one radius.
        // An apex is the region's tightest node, so the radius is unsettled around it and the walk has to travel out
        // to where the corner has released before it can stop. Returns the bound if it never settles.
        static int EntranceStep(int apexNode, int maxStep, int count)
        {
            for (int step = 1; step <= maxStep; step++)
            {
                int node = ARS.IsPointToPoint ? apexNode - step : Wrap(apexNode - step, count);
                if (ARS.IsPointToPoint && node < 0) break;
                if (HoldsOneRadius(node, -1, count)) return step;
            }
            return maxStep;
        }

        const int SpanStabilityNodes = 10;
        const float SpanMinimumMeters = 20f;
        const float SpanRadiusTolerance = 0.3f;
        const int SpanNodeLimit = 500;
        const float MaximumApexRadius = 200f;
        const float AlignedCornerSeconds = 8f;
        const float AlignedCornerDegrees = 15f;

        // Where a corner hands over to a consistent curve: the first node past the apex whose road holds one radius.
        // The apex is a local minimum, so this cannot fire beside it. Returns the bound if nothing settles.
        static int ExitStep(int apexNode, int maxStep, int count)
        {
            for (int step = 1; step <= maxStep; step++)
            {
                int node = ARS.IsPointToPoint ? apexNode + step : Wrap(apexNode + step, count);
                if (ARS.IsPointToPoint && node >= count) break;
                if (HoldsOneRadius(node, 1, count)) return step;
            }
            return maxStep;
        }

        // A span end must hand the car to a curve that is more open but constant, so the run beyond it holds one
        // radius, measured against its own mean so the tolerance means the same on a hairpin as on a sweeper.
        // Direction is the node step away from the apex.
        static bool HoldsOneRadius(int node, int direction, int count)
        {
            float total = 0f;
            for (int ahead = 0; ahead < SpanStabilityNodes; ahead++)
            {
                int sample = ARS.IsPointToPoint ? node + direction * ahead : Wrap(node + direction * ahead, count);
                if (sample < 0 || sample >= count) return false;
                total += OpenRoadRadius(sample);
            }
            float mean = total / SpanStabilityNodes;
            for (int ahead = 0; ahead < SpanStabilityNodes; ahead++)
            {
                int sample = ARS.IsPointToPoint ? node + direction * ahead : Wrap(node + direction * ahead, count);
                if (Math.Abs(OpenRoadRadius(sample) - mean) > mean * SpanRadiusTolerance) return false;
            }
            return true;
        }

        // Open road reads arbitrarily wide on a four-node chord, so it saturates on the sentinel the point carries.
        // Without that clamp the window mean explodes and no run ever settles.
        static float OpenRoadRadius(int node)
        {
            float radius = ARS.TrackPoints[node].PreciseCurveRadius;
            if (radius <= 0f || radius >= 999f || float.IsNaN(radius) || float.IsInfinity(radius)) return 999f;
            return radius;
        }

        // A merged survivor's extensions, re-walked rather than inherited: the entrance runs in over the absorbed
        // region to the same hard node limit a fresh region uses, and the exit is re-derived from the apex the
        // same way a fresh region's is, bounded by the absorbed region's end. The floor is capped by what is left of
        // each bound, so neither walk can pass it and a chain of merges stops at the first corner of the complex.
        static void ExtendMergedCorner(CornerPoint survivor, int unionStart, int unionEnd, int count)
        {
            int spanLimit = Math.Min(SpanNodeLimit, count - 1);
            int entranceDistance = Math.Min(ARS.IsPointToPoint ? survivor.Node - unionStart : Wrap(survivor.Node - unionStart, count), spanLimit);
            int entranceStep = EntranceStep(survivor.Node, entranceDistance, count);
            int entrance = ARS.IsPointToPoint ? survivor.Node - entranceStep : Wrap(survivor.Node - entranceStep, count);
            int exitDistance = Math.Min(ARS.IsPointToPoint ? unionEnd - survivor.Node : Wrap(unionEnd - survivor.Node, count), spanLimit);
            int exitStep = ExitStep(survivor.Node, exitDistance, count);
            int exit = ARS.IsPointToPoint ? survivor.Node + exitStep : Wrap(survivor.Node + exitStep, count);
            float minEntranceExit = Math.Min(SpanMinimumMeters, spanLimit);
            int entranceFloor = (int)Math.Min(minEntranceExit, entranceDistance);
            int exitFloor = (int)Math.Min(minEntranceExit, exitDistance);
            if ((ARS.IsPointToPoint ? survivor.Node - entrance : Wrap(survivor.Node - entrance, count)) < minEntranceExit)
                entrance = ARS.IsPointToPoint ? survivor.Node - entranceFloor : Wrap(survivor.Node - entranceFloor, count);
            if ((ARS.IsPointToPoint ? exit - survivor.Node : Wrap(exit - survivor.Node, count)) < minEntranceExit)
                exit = ARS.IsPointToPoint ? survivor.Node + exitFloor : Wrap(survivor.Node + exitFloor, count);
            survivor.StartNode = entrance;
            survivor.EndNode = exit;
            survivor.LengthStart = ARS.IsPointToPoint ? survivor.Node - entrance : Wrap(survivor.Node - entrance, count);
            survivor.LengthEnd = ARS.IsPointToPoint ? exit - survivor.Node : Wrap(exit - survivor.Node, count);
        }

        static float SmoothedRadius(int node, int count, int halfWindow)
        {
            float curvature = 0f;
            int samples = 0;
            for (int offset = -halfWindow; offset <= halfWindow; offset++)
            {
                int sample = ARS.IsPointToPoint
                    ? node + offset
                    : Wrap(node + offset, count);
                if (sample < 0 || sample >= count) continue;

                float radius = ARS.TrackPoints[sample].PreciseCurveRadius;
                if (radius <= 0f || radius >= 999f || float.IsNaN(radius) || float.IsInfinity(radius)) continue;
                curvature += 1f / radius;
                samples++;
            }

            return samples > 0 ? 1f / (curvature / samples) : 999f;
        }

        public static float Circumradius3D(Vector3 a, Vector3 b, Vector3 midpoint)
        {
            return Circumradius2D(new Vector2(a.X, a.Y), new Vector2(b.X, b.Y), new Vector2(midpoint.X, midpoint.Y));
        }

        public static float Circumradius2D(Vector2 a, Vector2 b, Vector2 midpoint)
        {
            Vector2 midpoint1 = (a + b) / 2;
            float dx1 = b.X - a.X;
            float slope1 = dx1 != 0f ? (b.Y - a.Y) / dx1 : float.PositiveInfinity;
            float perpendicular1 = slope1 != 0f ? -1 / slope1 : float.PositiveInfinity;
            Vector2 midpoint2 = (b + midpoint) / 2;
            float dx2 = midpoint.X - b.X;
            float slope2 = dx2 != 0f ? (midpoint.Y - b.Y) / dx2 : float.PositiveInfinity;
            float perpendicular2 = slope2 != 0f ? -1 / slope2 : float.PositiveInfinity;
            float denominator = perpendicular2 - perpendicular1;
            if (denominator == 0f || float.IsNaN(denominator) || float.IsInfinity(denominator)) return 999f;
            float centerX = (midpoint1.Y - midpoint2.Y + perpendicular2 * midpoint2.X - perpendicular1 * midpoint1.X) / denominator;
            float centerY = midpoint1.Y + perpendicular1 * (centerX - midpoint1.X);
            float radius = Vector2.Distance(new Vector2(centerX, centerY), a);
            return float.IsNaN(radius) || float.IsInfinity(radius) ? 999f : radius;
        }

        static int Wrap(int index, int count)
        {
            int wrapped = index % count;
            return wrapped < 0 ? wrapped + count : wrapped;
        }

        public static void BuildTrackLimits(List<Vector3> nodes, Dictionary<int, float> widths, XmlDocument trackFile, ref bool isPointToPoint, List<Prop> startFlares)
        {
            if (nodes.Count == 0) return;
            isPointToPoint |= nodes[0].DistanceTo(nodes[nodes.Count - 1]) > 20f;
            Color? flareColor = ReadFlareColor(trackFile);

            if (startFlares.Count == 0 && flareColor.HasValue) SpawnStartGates(nodes, widths, startFlares, flareColor.Value);
            Function.Call(Hash.CLEAR_FOCUS);
        }

        // Built to order rather than to a fixed ceiling: the grid needs slots for the size being spawned plus two
        // that GridBuilder.Place reads ahead into, and the size can change between spawns, so it is redone each time.
        public static void BuildGridSlots(List<Vector3> nodes, Dictionary<int, float> widths, bool isPointToPoint, int wantedCars, List<Vector3> grid)
        {
            grid.Clear();
            if (wantedCars <= 0) return;

            int slotCount = wantedCars + 2;
            if (isPointToPoint) BuildPointToPointGrid(nodes, widths, grid, slotCount);
            else BuildCircuitGrid(nodes, widths, grid, slotCount);
        }

        static void SpawnStartGates(List<Vector3> nodes, Dictionary<int, float> widths, List<Prop> limits, Color color)
        {
            // The line is the last node in both modes: a circuit wraps there and a point-to-point finishes across it.
            int last = nodes.Count - 1;
            SpawnGatePair(nodes[last], nodes[last] - nodes[Wrap(last - 1, nodes.Count)], widths.ContainsKey(last) ? widths[last] : widths[0], limits, color);
        }

        static void SpawnGatePair(Vector3 position, Vector3 direction, float width, List<Prop> limits, Color color)
        {
            // Offsets come from the direction, never from the prop's own right vector: that one is parallel to the track once its heading has been turned 90.
            Vector3 across = Quaternion.RotationAxis(Vector3.WorldUp, (float)Math.PI / 180f * -90f) * new Vector3(direction.X, direction.Y, 0f).Normalized;
            for (int side = -1; side <= 1; side += 2)
            {
                Prop gate = World.CreateProp("prop_flare_01b", position + across * width * side + new Vector3(0f, 0f, 0.05f), new Vector3(0, 0, direction.Normalized.ToHeading() + 90f), false, false);
                QueueFlare(gate, color);
                gate.FreezePosition = true;
                gate.HasCollision = false;
                limits.Add(gate);
            }
        }

        static void BuildPointToPointGrid(List<Vector3> nodes, Dictionary<int, float> widths, List<Vector3> grid, int slotCount)
        {
            for (int i = slotCount + 1; i > 1 && i * 3 < nodes.Count; i--)
            {
                Vector3 point = nodes[i * 3];
                Vector3 direction = (point - nodes[i * 3 - 1]).Normalized;
                grid.Add(point - Quaternion.RotationAxis(Vector3.WorldUp, (float)Math.PI / 180f * -90f) * (direction * ((i % 2 == 1) ? widths[0] * 0.45f : -widths[0] * 0.45f)));
            }
        }

        static void BuildCircuitGrid(List<Vector3> nodes, Dictionary<int, float> widths, List<Vector3> grid, int slotCount)
        {
            int reference = nodes.Count - 1;
            for (int i = nodes.Count - 1; i > 50 && grid.Count < slotCount; i--)
            {
                if (i >= reference - 5) continue;
                Vector3 direction = (nodes[reference] - nodes[i]).Normalized;
                grid.Add(nodes[i] - Quaternion.RotationAxis(Vector3.WorldUp, (float)Math.PI / 180f * -90f) * (direction * ((grid.Count % 2 == 1) ? -widths[0] * 0.45f : widths[0] * 0.45f)));
                reference = i;
            }
        }

        static Color? ReadFlareColor(XmlDocument trackFile)
        {
            string value = trackFile?.SelectSingleNode("//Trackside") is XmlElement element ? element.GetAttribute("Flares") : "";
            if (value == "false") return null;
            int rgb;
            return value.Length == 9 && int.TryParse(value, out rgb) ? Color.FromArgb(int.Parse(value.Substring(0, 3)), int.Parse(value.Substring(3, 3)), int.Parse(value.Substring(6, 3))) : Color.GreenYellow;
        }

        const string FlarePtfxAsset = "scr_apartment_mp";
        const string FlarePtfxEffect = "scr_finders_package_flare";
        static readonly List<KeyValuePair<Prop, Color>> QueuedFlares = new List<KeyValuePair<Prop, Color>>();

        // A named ptfx asset streams over frames, so the effect cannot start in the same tick it is requested.
        static void QueueFlare(Prop prop, Color color)
        {
            QueuedFlares.Add(new KeyValuePair<Prop, Color>(prop, color));
        }

        public static void TickQueuedFlares(List<int> effects)
        {
            if (QueuedFlares.Count == 0) return;
            if (!Function.Call<bool>(Hash.HAS_NAMED_PTFX_ASSET_LOADED, FlarePtfxAsset))
            {
                Function.Call(Hash.REQUEST_NAMED_PTFX_ASSET, FlarePtfxAsset);
                return;
            }

            for (int i = QueuedFlares.Count - 1; i >= 0; i--)
            {
                Prop prop = QueuedFlares[i].Key;
                Color color = QueuedFlares[i].Value;
                QueuedFlares.RemoveAt(i);
                if (!ARS.CanWeUse(prop)) continue;

                Function.Call(Hash._SET_PTFX_ASSET_NEXT_CALL, FlarePtfxAsset);
                int effect = Function.Call<int>(Hash.START_PARTICLE_FX_LOOPED_ON_ENTITY, FlarePtfxEffect, prop, 0f, 0f, 0.1f, 0f, 0f, 0f, 1f, true, true, true);
                if (effect == 0)
                {
                    ARS.Log(ARS.LogImportance.Info, "Flare: " + FlarePtfxEffect + " did not start from " + FlarePtfxAsset);
                    continue;
                }
                Function.Call(Hash.SET_PARTICLE_FX_LOOPED_ALPHA, effect, 1f);
                Function.Call(Hash.SET_PARTICLE_FX_LOOPED_COLOUR, effect, color.R / 255f, color.G / 255f, color.B / 255f, 1f, true);
                effects.Add(effect);
            }
        }
    }
}
